single_leg_velocity_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
     - hip
     - knee

single_leg_effort_controller:
  type: effort_controllers/JointGroupEffortController
  joints:
     - hip
     - knee

# Publish all joint states ----------------------------------
joint_state_controller:
   type:         joint_state_controller/JointStateController
   publish_rate: 125